---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nacosbridge-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/finalizers
  - configmaps/status
  - nodes
  - nodes/finalizers
  - nodes/status
  - services
  - services/finalizers
  - services/status
  verbs:
  - '*'
